config/routes.rb
Rails.application.routes.draw do
  get "ask", to: "questions#ask", as: :ask
  get "answer", to: "questions#answer", as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
      
  end  

  def answer
    @question = params[:question]
    if @question.blank?
      @answer = "Não consigo te ouvir"
    elsif @question.downcase == "i am going to work"
      @answer = "É nóis! Vamo lá!"
    elsif @question.ends_with?("?")
      @answer = "Que pergunta imbecil! Se troca e vamo malhar!"
    else
      @answer = "Não quero nem saber, se troca e vamo malhar!"
    end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Técnico Imbecil</h1>

  <p>
    <% if @question.blank? %>
      😶
    <% else %>
      <%= @question %>
    <% end %>
  </p>
  <p><i>VOCÊ</i></p>

  <p><%= @answer %></p>
  <p><i>IMBECIL DO TÉCNICO IMBECIL</i></p>

<%= link_to "Pergunte outra coisa", ask_path %>

app/views/questions/ask.html.erb
<h1>PERGUNTA PRO TÉCNICO IMBECIL</h1>

<p>Faça qualquer pergunta para o técnico imbecil</p>

<form action="/answer">
    <input type="text" name="question" placeholder="Digite aqui sua pergunta">
    <input type="submit" value="ask">
</form>